# Generated by Django 3.0.3 on 2020-03-25 01:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('xamine', '0002_order'),
    ]

    operations = [
        migrations.CreateModel(
            name='Level',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32)),
            ],
        ),
        migrations.AddField(
            model_name='order',
            name='level',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='xamine.Level'),
            preserve_default=False,
        ),
    ]
