# Generated by Django 3.0.5 on 2020-04-06 00:02

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('xamine', '0004_auto_20200403_1946'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='allergy_asthma',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='patient',
            name='allergy_dye',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='patient',
            name='birth_date',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='patient',
            name='email_info',
            field=models.EmailField(default=False, max_length=254),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='patient',
            name='latex',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='patient',
            name='mri_dye',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='patient',
            name='phone_number',
            field=models.CharField(default=2128675309, max_length=10),
            preserve_default=False,
        ),
    ]
