# Generated by Django 3.0.5 on 2020-04-06 01:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('xamine', '0005_auto_20200405_2002'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='notes',
            field=models.TextField(blank=True, null=True),
        ),
    ]
