# Generated by Django 3.0.5 on 2020-04-06 02:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('xamine', '0006_patient_notes'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='report',
            field=models.TextField(blank=True, null=True),
        ),
    ]
