# Generated by Django 3.0.5 on 2020-04-06 21:22
""" This adds the levels for Orders """

from django.db import migrations



class Migration(migrations.Migration):

    dependencies = [
        ('xamine', '0007_order_report'),
    ]

    operations = [
    ]
