# Generated by Django 3.0.5 on 2020-04-06 22:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('xamine', '0010_auto_20200406_1819'),
    ]

    operations = [
        migrations.RenameField(
            model_name='patient',
            old_name='latex',
            new_name='allergy_latex',
        ),
    ]
