# Generated by Django 3.0.5 on 2020-04-07 00:39

from django.db import migrations, models
import xamine.models


class Migration(migrations.Migration):

    dependencies = [
        ('xamine', '0012_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='image',
            field=models.FileField(default='', upload_to=xamine.models.image_path),
            preserve_default=False,
        ),
    ]
