# Generated by Django 3.0.5 on 2020-04-07 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('xamine', '0015_testmodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='appointment',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
