# Generated by Django 3.0.5 on 2020-04-08 15:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('xamine', '0017_auto_20200408_1054'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='doctor',
            field=models.ForeignKey(default=10, on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
