# Generated by Django 3.0.5 on 2020-04-17 03:11

from django.db import migrations
import phone_field.models


class Migration(migrations.Migration):

    dependencies = [
        ('xamine', '0019_orderkey'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='phone_number',
            field=phone_field.models.PhoneField(max_length=31),
        ),
    ]
