# Generated by Django 3.0.5 on 2020-04-17 03:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('xamine', '0020_auto_20200416_2311'),
    ]

    operations = [

    ]
