# Generated by Django 3.0.5 on 2020-04-17 22:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('xamine', '0023_auto_20200416_2354'),
    ]

    operations = [

    ]
