# Generated by Django 3.0.5 on 2020-04-21 22:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('xamine', '0029_auto_20200421_1830'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='completed',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
    ]
