# Generated by Django 3.0.5 on 2020-04-23 23:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('xamine', '0031_auto_20200423_1827'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='notes',
            field=models.TextField(blank=True, null=True),
        ),
    ]
