# Generated by Django 3.0.5 on 2020-04-23 23:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('xamine', '0032_order_notes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='imaging_needed',
            field=models.CharField(default='', max_length=128),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='order',
            name='modality',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='xamine.ModalityOption'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='order',
            name='visit_reason',
            field=models.CharField(default='', max_length=128),
            preserve_default=False,
        ),
    ]
