# Generated by Django 3.0.5 on 2020-04-29 19:04

from django.db import migrations, models
import xamine.models
import xamine.validators


class Migration(migrations.Migration):

    dependencies = [
        ('xamine', '0036_auto_20200428_2144'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='image',
            field=models.FileField(upload_to=xamine.models.image_path, validators=[xamine.validators.validate_file_size]),
        ),
    ]
