# Generated by Django 3.0.5 on 2020-04-30 02:25

from django.db import migrations, models
import xamine.validators


class Migration(migrations.Migration):

    dependencies = [
        ('xamine', '0038_auto_20200429_1519'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='birth_date',
            field=models.DateField(validators=[xamine.validators.check_past_date]),
        ),
    ]
